// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "shilovmo@st.tech"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/techdata": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Получить технические характеристики",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Получение данных данных"
                ],
                "summary": "Получить технические характеристика автомобилей",
                "operationId": "get-techdata",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.TechData"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.TechData": {
            "type": "object",
            "properties": {
                "Data": {
                    "$ref": "#/definitions/model.TechDataObj"
                }
            }
        },
        "model.TechDataObj": {
            "type": "object",
            "properties": {
                "ЗначениеСвойства": {
                    "type": "string"
                },
                "Ид": {
                    "type": "integer"
                },
                "ИдЗначенияСвойства": {
                    "type": "integer"
                },
                "ИдКатегории": {
                    "type": "integer"
                },
                "ИдРодителя": {
                    "type": "integer"
                },
                "ИдСвойства": {
                    "type": "integer"
                },
                "Категория": {
                    "type": "string"
                },
                "Модель": {
                    "type": "string"
                },
                "НаименованиеРодителя": {
                    "type": "string"
                },
                "НаименованиеСвойства": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "https://onsales.st.tech",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API СТТ",
	Description:      "API-сервер СТТ",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
