basePath: /
definitions:
  model.TechData:
    properties:
      Data:
        $ref: '#/definitions/model.TechDataObj'
    type: object
  model.TechDataObj:
    properties:
      ЗначениеСвойства:
        type: string
      Ид:
        type: integer
      ИдЗначенияСвойства:
        type: integer
      ИдКатегории:
        type: integer
      ИдРодителя:
        type: integer
      ИдСвойства:
        type: integer
      Категория:
        type: string
      Модель:
        type: string
      НаименованиеРодителя:
        type: string
      НаименованиеСвойства:
        type: string
    type: object
host: https://onsales.st.tech
info:
  contact:
    email: shilovmo@st.tech
    name: API Support
  description: API-сервер СТТ
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: API СТТ
  version: "1.0"
paths:
  /auth/techdata:
    get:
      consumes:
      - application/json
      description: Получить технические характеристики
      operationId: get-techdata
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TechData'
      security:
      - ApiKeyAuth: []
      summary: Получить технические характеристика автомобилей
      tags:
      - Получение данных данных
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
